# Generated by Django 3.0.8 on 2020-07-23 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_passanger'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passanger',
            new_name='Passenger',
        ),
    ]
